schema_version: 1

context:
  version: "5.1.10"
  build_number: 0

recipe:
  name: pyami-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyami-core/pyami_core-${{ version }}.tar.gz
  sha256: 6563f57f111059875115cf64bee8c2a737f6c4a87a247a52f9a13c037eee868b
  patches:
    - patches/0001-guard-module-level-entrypoint.patch

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: pyami-core
      version: ${{ version }}
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - lxml
    tests:
      - python:
          imports:
            - pyAMI
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"

  - package:
      name: pyami-core-cli
      version: ${{ version }}
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      python:
        entry_points:
          - ami=pyAMI.app:main
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - pyami-core
    tests:
      - script:
          - ami --help
        requirements:
          run:
            - python ${{ python_min }}.*


about:
  summary: Python ATLAS Metadata Interface (pyAMI)
  homepage: https://atlas-ami.cern.ch/
  repository: https://github.com/ami-team/pyAMI-core
  documentation: https://atlas-ami.cern.ch/docs/pyAMI/
  license: LGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kratsg
